<h4><a href="http://helios.ite.gmu.edu/~kyoon5/IT207/introduction/">&nbsp;&nbsp;&nbsp;Home</a></h4>
<h4>&nbsp;&nbsp;&nbsp;Assignments</h4>
<ul>
  <li><a href="/~kyoon5/IT207/introduction/assignment1/">Assignment 1</a></li>
  <li><a href="/~kyoon5/IT207/introduction/assignment2/">Assignment 2</a></li>
  <li><a href="/~kyoon5/IT207/introduction/assignment_3/">Assignment 3</a></li>
  <li><a href="/~kyoon5/IT207/introduction/assignment_4/">Assignment 4</a></li>
</ul>
<h4>&nbsp;&nbsp;&nbsp;Practica</h4>
<ul>
  <li><a href="/~kyoon5/IT207/introduction/labPracticum1/">Lab Practicum 1</a></li>
  <li><a href="/~kyoon5/IT207/introduction/labPracticum_2/login.php">Lab Practicum 2</a></li>
</ul>